### ISSUE TITLE
Card Holder bug

### ISSUE THREAD

**Issue by bigtruckin78** [Direwolf20-MC/LaserIO#214] opened 2023-11-12 01:17 UTC
### LaserIO version

1.6.6

### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Modpack & Version

ATM 9 0.2.12

### Do you have optifine installed?

No

### Describe the issue

When you open up the menu of an installed energy card the card holder sub menu goes away. Would be nice if it stayed open to maintain access to overclockers

### Steps to reproduce

1. Have card holder in inventory when you access an energy card. The card holder sub-menu doesn't come up. Should stay open to maintain access to overclockers. 

### Expected behaviour

Sub-menu should stay open while accessing energy card

**Comment by Direwolf20-MC** [comment] 2023-11-12 03:24
Duplicate of #206

**Closed by Direwolf20-MC** 2023-11-12 03:24 UTC
Labels: bug
