### ISSUE TITLE
IndexOutOfBounds pressing the - (remove) button in empty tag filter

### ISSUE THREAD

**Issue by TheGoldenProof** [Direwolf20-MC/LaserIO#172] opened 2023-03-19 17:45 UTC
### LaserIO version

1.5.2

### Minecraft Version

1.19.2

### Forge Version

43.2.6

### Modpack & Version

All The Mods 8

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

see title

### Steps to reproduce

1. open tag filter
2. press the - (remove) button with nothing in the list of tags
3. game crash

### Expected behaviour

nothing happens, no game crash

### Log files

https://pastebin.com/bBEnNJbS

**Comment by IONayrus** [comment] 2023-03-19 18:07
I also got this bug.

But i could only reproduce it in Atm8 and nowhere else. I couldn't find any array access in the code so i figured it had something to do with the pack and didnt open an issue

**Comment by TheGoldenProof** [comment] 2023-03-19 18:22
> I couldn't find any array access in the code
```
if (selectedSlot != -1) {
    tags.remove(displayTags.get(selectedSlot));
    selectedSlot = -1;
}
```
its the `displayTags.get`. The selected slot stuff seems like it should be preventing this from happening, but something must be going wrong that causes the selected slot to be 0, not -1, even when there are no tags.

**Comment by Direwolf20-MC** [comment] 2023-03-19 18:47
I wonder if this is also the reason that the fluid filter ui doesn’t work in atm8. Something is doing weird things to other mods screens. I haven’t been able to figure out which mod is causing it. If anyone does please let me know.

**Comment by Direwolf20-MC** [comment] 2023-06-22 20:59
Cannot reproduce (at least in 1.20) so closing for now. Please let me know if you can reproduce it again :D

**Closed by Direwolf20-MC** 2023-06-22 20:59 UTC
Labels: bug
