### ISSUE TITLE
Disappearing Cards

### ISSUE THREAD

**Issue by Karma-Fox** [Direwolf20-MC/LaserIO#76] opened 2022-07-03 02:18 UTC
### LaserIO version

1.3.0

### Minecraft Version

1.18.2

### Forge Version

40.1.47

### Modpack & Version

Direwolf20 1.18.2 1.5.1

### Do you have optifine installed?

No

### Describe the issue

Cards are disappearing from the Card Holder. This has happened to me twice now. The first time, I wasn't too sure and thought I was remembering wrong, this time I had over 32 of each type of card in the Card Holder.

### Steps to reproduce

Have no clue what is causing this so don't know steps to reproduce.

### Expected behaviour

Cards should not just randomly disappear into the void.

### Log files

Nothing in the log. Also not exactly sure when the cards disappeared.

### Additional information

I really don't like posting a bug report with so little information but I really am at a loss on how this keeps happening or even when it happens as I can go days without opening the Card Holder.

**Comment by jinks** [comment] 2022-07-10 03:42
I might have some tenuous information to add...

I'm not actually 100% sure this is what happened, but I *think* what I did was the following:
- the holder was in my backpack, set to collect mode
- I had 4 fresh item cards in my inventory, and a bunch of each type in the holder
- I opened my backpack, grabbed the holder to the muse, set it down in my inventory and immediately picked it back up when it had collected the cards
- next time I worked on a node *only* those 4 cards were left in the holder

So my best guess is it's got something to do with collect mode and moving it from an unloaded inventory to the player inventory without further interacting with it.

**Comment by Karma-Fox** [comment] 2022-07-11 03:43
After some more testing, I have figured out what the cause of the problem is.....creative mode. If you go into creative mode, the entire card holder gets cleared out. I have lots hundreds of cards this way.

**Comment by jollycar** [comment] 2022-07-14 22:20
I can't reproduce this. I switched multiple times from survival to creative and the cards stay in the cardholder

Could you give the exact Steps to reproduce?

**Comment by Karma-Fox** [comment] 2022-07-15 01:16
Not really. I mean, I am using the Direwolf20 1.5.1 pack on a server with current LaserIO version (1.3.1 now), and anytime I go into creative and back to survival, I notice all of the cards in my card holder are completely gone.

**Comment by Direwolf20-MC** [comment] 2022-07-18 02:10
I also can't reproduce - if you can please give exact steps to cause it, that'd be helpful :)

**Comment by Karma-Fox** [comment] 2022-07-18 04:51
I provided the only steps I know of in previous response. Only thing I can say is this is happening every single time, without fail, on my private server. I don't know what else to say here.

**Comment by Direwolf20-MC** [comment] 2022-07-18 22:37
Can you try updating to the latest version (1.3.2) and then get yourself a new card holder, and see if it keeps happening?

**Comment by NeQuissimus** [comment] 2022-07-28 16:37
I can confirm that this happens. I do not have a consistent reproducer but I believe it only happens once after a server restart. (Running Direwolf20 1.18 1.7.0, so LaserIO 1.3.1)

- Have an empty card holder in your inventory, set to auto-grab cards from inventory
- Craft cards, card holder takes them
- `/gamemode creative`
- `/gamemode survivial`
- Put card holder from inventory into hotbar and open
- Card holder is empty

Without a server restart, the cards are just fine and stay in the card holder.
With a server restart, the cards usually disappear once but even that does not seem to be 100% consistent.

**Comment by Direwolf20-MC** [comment] 2022-07-28 16:57
Can you try crafting a new card holder and make sure you’re on the latest version?

**Comment by NeQuissimus** [comment] 2022-07-28 17:08
Unfortunately, we've had issues with version 1.8.0 of the pack on macOS. Not sure yet why (nothing on the Minecraft main menu is clickable) but we had to revert back to 1.7.0. I should be able to just drop the 1.3.2 JAR into the server folder, right?
I'll run a quick test this weekend and see if I cannot figure out a solid reproducer.

**Comment by Direwolf20-MC** [comment] 2022-08-01 20:31
And make sure all your clients update too :)

**Comment by NeQuissimus** [comment] 2022-08-02 18:11
It looks like the disappearing cards are an issue with old card holders (?)
I did a couple of things:
- (LaserIO 1.3.1) Old card holder, go creative and back - Cards disappeared once, never again (2 out of 3 server restarts)
- (LaserIO 1.3.1) Restart server, crafted a new card holder, added cards, creative mode and back - everything fine (2x)
- (LaserIO 1.3.2) Restart server, "new" card holder (crafted with 1.3.1) from previous test was fine
- (LaserIO 1.3.2) Entirely new card holder (crafted with 1.3.2), creative mode and back - everything fine

It would appear it's now a non-issue for me :)

**Comment by Direwolf20-MC** [comment] 2022-08-03 16:35
Sounds good! :) Let me know if you can make it happen with a newer version of the mod and a new card holder.

**Closed by Direwolf20-MC** 2022-08-03 16:35 UTC
Labels: bug
